theme: jekyll-theme-minimal

title: todler time 
description: For todlers/children/adults fun timers/calendars/clocks
show_downloads: false
github:
  is_project_page: false
nav_links:
  - title: Timer
    url: timer.html
